name: CI (Validate → Build → Deploy)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    name: Validate Controllers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Validate controllers
        run: npm run validate

  build:
    name: Build Step
    needs: validate
    runs-on: ubuntu-latest
    if: ${{ needs.validate.result == 'success' }}
    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Compile project
        run: npm run build || echo "No build script defined"

  deploy:
    name: Deploy Step
    needs: build
    runs-on: ubuntu-latest
    if: ${{ needs.build.result == 'success' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Deploy
        run: echo "Desplegando aplicación..."
